---
# handlers file for hadoop-worker

- name: restart hadoop datanode
  shell: |
    source /etc/profile.d/hadoop.sh
    /usr/local/hadoop/bin/hdfs --daemon stop datanode
    sleep 2
    /usr/local/hadoop/bin/hdfs --daemon start datanode
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ ansible_user }}"

- name: restart hadoop nodemanager
  shell: |
    source /etc/profile.d/hadoop.sh
    /usr/local/hadoop/bin/yarn --daemon stop nodemanager
    sleep 2
    /usr/local/hadoop/bin/yarn --daemon start nodemanager
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ ansible_user }}"